# Organize {#organize}

`r newthought("If you are using R to write")` for larger projects, including
research for academic papers and theses, you should start putting some thought
into how you organize your research files, including raw data, cleaned data,
coding scripts for analysis, and output like paper drafts and figures. So far,
you may have run much of your analysis within a single R script or R Markdown
file. Often, any associated data are within the same working directory as your
script or R Markdown file, but the files for one project are not separated from
files for other projects. As you move to larger projects, this kind of set-up
won't work as well. Instead, you'll want to start keeping all materials for a
project in a single and exclusive directory.


## R Projects

`r newthought("RStudio allows you to")` create "Projects", which help with this
organization. An R Project is very simple---it's just a file directory, with an
extra subdirectory added to the directory [with settings?]. This directory is
saved as a **dot file**^[**dot file.** ...], so you probably won't be able to see it
listed if you look at the directory contents using your [file viewer?]. If you'd like
to see the listing (or delete it by hand, although you likely won't ever need to 
do this), check the settings for your [file viewer?], and see if you have the option 
to show all files. Alternatively, you can use the "list" command with the "all" option
(`ls -a`) at a Bash shell to view all files and subdirectories in a directory. 

Advantages of setting a directory to be an R Project are: 

- Automatically uses the directory as your current working directory when you open the project. 
- Coordinates well with git version control and GitHub repository system. 
- Opens a "Files" window for navigating project files in an RStudio pane when you open the project. 

You can either create an R Project as a new directory or convert an existing directory into 
an R Project. To do either, in RStudio go to the "File" menu and select "New Project". You'll 
then have the option to either create a new directory that's an R Project or to search through
your computer's files to find an existing directory to make into an R Project. 

Once you've created an R Project, you can open it in RStudio; opening an R Project will set 
the project's directory as your working directory, opening a "Files" window with all the
subdirectories and files in the project directory and allowing you to run code with 
**relative filenames**^[**relative filename.** ...] from the project's directory. If you 
share the R Project with someone else,^[One way to do this would be to zipped the directory
into a single file and share it by email. Another is to use git version control, post the
directory to GitHub, and share the directory from there.] he or she will also be able to 
open the R project using RStudio. 

One benefit of R Projects is that it is very easy to initialize them as git repositories. 
A later section ("Track") will go over how to initialize and use git version control for
R Projects. You will also definitely want to use an R Project for any R package you write, 
as this will introduce a lot of functionality that "plays well" with the `devtools` package
to make it easier to write, build, and publish an R package [?]. 

## Directory organization

...



### Keeping things tidy

My desk at work is very messy, with lots of paper printouts piled up. My car and my closet 
aren't terribly tidy, either. But I do keep my project directories very tidy, and I 
strongly recommend the practice. 

This goes beyond "well-organized", which we just covered (putting all project
files in one directory, using subdirectories to divide up files in a project,
using consistent names for project file directories, etc.). Keeping a project
directory "tidy" means having **only one** version of each file. Often, as you
develop a project, especially when collaborators are involved, you can end up
with many versions of a file. For example, you may have the draft of a journal
article's text saved in some versions with the file name reflecting the date of
the draft ("draft_may_12.docx"), some versions that include the initials of
people who reviewed it ("paper_draft_ba_rp_mb2.docx"), and so on.

This type of organization---having multiple versions of project files, with the
file names meant to help you keep track of them---results in very cluttered and
hard-to-manage project directories. Instead, at any given moment, each of your
project directories should have only one version of each project file. You
certainly won't want to lose information from edits and changes to the files
along the way, so it's smart to use some type of **version control
system**[**version control system.** Software for tracking changes to software
projects. Some researchers who use a lot of coding also use this software to
track their projects One well-known example is **git**, but there are other
version control systems as well.] on each project directory. This will allow you
to track the changes you've made to each file and to go back and revisit the
file at any moment in the project's history. A later section of this booklet
("Track") will describe how you can use `git` for version control for R
projects.

### Avoiding repetition

One key to efficient organization is to **avoid repetition**.^[In programming,
you'll often hear this advice as "Do Not Repeat Yourself".] In practice, it
often happens that you're using the same code across several projects. For
example, say you have some code that calculates the apparent temperature from
air temperature and some measure of dewpoint temperature. If you have organized
your project files to have one directory per paper, with all the associated code
for a paper within the project's directory, then you may find you're often
copying and pasting the code to calculate apparent temperature into different
directories.

This situation makes for a tricky balance---you want to organize your files and
have a separate directory for each project, but cutting and pasting code can be
a recide for disaster. Each time you move the code, there's a chance for an
error to slip in. Also, what if you want to make a change in the code? Say you
hear about a better algorithm for calculating apparent temperature? You will
either need to go through all of your projects that use that code and change the
code everywhere, or you will have to settle for different projects using
different algorithms.

This means it's time to start thinking about writing your own R package. You do
not have to publish every R package you write---it's fine to just use it
yourself and not share it more widely. Regardless, a package is the right place
to store related code that you use often, as well as documentation (and possibly
tests) to go with that code. A later section of this booklet ("Package") will go
over a bit about how to write your own R packages, as well as references for
learning more about package development.

## Learn more

[R Reproc. Research] is an excellent book with advice on improving the reproducibility of 
projects using R, including academic research projects. 

A few good articles have come out recently that describe project organization within 
the scientific fields of [biology] and [archaeology]. [One has links to example repositories?]  
Other papers discuss project organization in the context of reproducibility, presenting 
the idea of creating a **research compendium**^[**research compendium.** ...] for scientific
publications. 