# Package {#package}

`r newthought("As with many other things in R,")` the threshold of complexity
for writing your own package has recently lowered dramatically. If you are writing
some of your own functions in R to use for your research, and you've become comfortable
with writing functions, you should try putting them in an R package. You don't have
to share this package through publishing it on CRAN or another repository---instead, it's 
fine to start by just writing packages for your own use, or for your research group's 
private use. However, once you start writing packages, you will see how straightforward
it is, and you may want to take the extra steps to prepare your package for CRAN and 
submit it.

## R packages

### R code

[Where to put it]

[How to add documentation]

### DESCRIPTION file

- License

### Other package components

So far, I've described the barebones elements you'll need to have to create a very 
minimalist package. There are, however, a number of other elements you'll often 
want to add to the package. As with the R code for package functions and the 
DESCRIPTION file, there is a specific location and format required for each of 
these elements within an R package. 

Some of the most common components you'll want to add are: 

- **Example data.**
- **Vignettes.**
- **Unit tests.**

To help you set up these extra components, 
you may want to take a look at the `use_*` family of functions in the `usethis`
[@R-usethis]
package^[The `use_*` family of functions were previously in the `devtools` package, but they 
are being deprecated there and moved to the `usethis`
package. The [R Packages](http://r-pkgs.had.co.nz/) book was written before they were deprecated 
in `devtools`, and so it discusses them as `devtools` functions. As long as you install and load
the `usethis` package, though, you'll have no problem following along with the examples in 
that book.] For example, if you want to include example data in your package, 
you should check out the `use_data` function, while if you want to add unit tests to your
package, check out the `use_test` function. When you run one of these, you'll notice that the
function *adds files and subdirectories* when needed to your R package directory. This may 
throw you at first, since most R functions don't make changes to your file directory, but 
you'll need those added files to add the package components, and it's *much* easier to 
remember a single function call to run when you need to add one than to remember all the
details of which files and in what structure need to be added. 


## Publishing

### Why publish your packages?


### Where to publish packages


### Extra steps for publishing

If you want to submit your package to CRAN, you'll need to take a few extra steps
to get it ready. These steps aren't necessary for a package you plan to just
use privately, but they wouldn't be a bad idea to try to do even in that case. 

First, you'll need to make sure that the functions in your package are 
comprehensively documented. [What are requirements for this for CRAN?]

In addition to documenting specific functions, you should also consider
writing overall tutorials that walk a user through how to use your 
package in a few example scenarios. **vignette**^[**vignette.** ...]

You will also need to make sure that your package can run on different 
operating systems. If your package only has functions written exclusively 
in R, and doesn't interact with [the computer system?] or other programs
on your computer, this shouldn't be an issue. However, you should still 
check. [Travis CI, winbuilder]

[CRAN checks]

## Checking

## Try it out

- Create a new R Project for an R package
- Move a function into the right place in the package
- Edit the DESCRIPTION file as needed
- Build the package
- Add example data into the right place in the package
- Add some unit tests for the function
- Add documentation using roxygen2 notation
- Add a short vignette 

## Learn more

One wonderful resource for writing and publishing R packages is the book [R
Packages](http://r-pkgs.had.co.nz/) by Hadley Wickham. This book is available
for a reasonable price in paperback (many Barnes & Nobles carry it in their
computer section) and is also available for free online. The author of this book
also created and maintains the **`devtools` package**^[**`devtools` package.**
An R package with functions that facilitate R package development. These
functions are well-documented in the package documentation as well as through
the book [R Packages](http://r-pkgs.had.co.nz/). This package also includes a
function for installing R packages from code posted on GitHub
(`install_github`), which is very useful if you want to find and use packages
that are not yet available on CRAN and other repositories or if you want to use
the latest, "development" version of a package. This package is available on
CRAN and so can be installed with `install.packages("devtools")`.]

- ROpenSci handbook
- Official R documentation
- Coursera, Leanpub
