# Collect {#collect}

`r newthought("For Environmental Health researchers, I think")` one of the most exciting 
developments in R recently is how it is changing how we can collect data, both for 
exposures and outcomes. One direction for this development is how researchers can 
collect and measure original data from experiments, including through new measurement
technologies (e.g., phone-based Apps) and through new or rapidly changing health-related 
measurements (e.g., metabolomics, flow cytometry) and associated open-source 
software. 

R is also facilitating and leveraging rapid developments in how researchers can access and
query secondary data, including from [large admin databases?] and [data repositories
encouraged or required for some NIH-funded projects]. ... This section will provide an 
introduction to some of the ideas and techniques behind these developments for 
collecting secondary or public-use data for environmental health research, as well as
give you somee directions on where to go to find R packages that facilitate collecting
open data from R.



## Open data

A range of environmental datasets are available online, especially through national agencies. 
For example, [NOAA] provides various weather datasets, while USGS has data on water quality, 
[others]

You can visit webpages hosted by these agencies where you can download the datasets you need. 
However, this process can become tedious if you need lots of datasets, as may be the case for 
large studies incorporating many cities. Further, downloading the datasets "by hand" is hard 
to make reproducible, unless you meticiously write down all the steps you took as you visited 
the website. This means that your process will be harder for you to repeat in the future
or for others to replicate. 

A growing collection of R packages are now available that allow you to download datasets 
available online directly from R. This means that you can write an R script for your data
collection, making this step both better documented and more reproducible. ...

Further, there are now a number of R packages that provide access to open datasets that the 
package maintainer collected and processed and is now making available as an R package. 
[More on R data packages.]

### [Admin databases?]

Data collected by government groups like EPA, NOAA, USGS. 

### [Research repositories?]

Here, especially health-related data. 
NIH-supported (e.g., Metabolomics Workbench).
NHANES?

## Web services [?]

## ROpenSci

One of the best places to explore R packages for accessing open data for science is 
[**ROpenSci**](https://ropensci.org/).^[[**ROpenSci**](https://ropensci.org/). ...]
Many of its packages facilitate access to databases of open data relevant to scientific
research that have API access [?]. You can browse through its packages on 
its [**Packages** page](https://ropensci.org/packages/) 

Examples of some packages relevant to collecting data for environmental health research 
include: 

- bomrang: Australian Government Bureau of Meteorology ('BOM') Data Client
- clifro: Easily Download and Visualise Climate Data from CliFlo
- dbhydroR: 'DBHYDRO' Hydrologic and Water Quality Data
- essurvey: Download Data from the European Social Survey on the Fly
- FedData: Functions to Automate Downloading Geospatial Data Available from Several Federated Data Sources
- camsRad: R Client for CAMS Radiation Service
- ccafs: CCAFS GCM Data R Client
- dbhydroR: R interface to the South Florida Water Management District's DBHYDRO Database
- biomartr: Genomic Data Retrieval
- clifro: Easily Download and Visualise Climate Data from CliFlo
- DataSpaceR: An R Interface to 'the CAVD DataSpace'
- essurvey: Download Data from the European Social Survey on the Fly
- fingertipsR: Fingertips Data for Public Health
- getCRUCLdata: Use and Explore 'CRU' 'CL' v. 2.0 Climatology Elements
- getlandsat: Get Landsat 8 Data from Amazon Public Data Sets
- googleLanguageR: Call Google's 'Natural Language' API, 'Cloud Translation' API, 'Cloud Speech' 
API and 'Cloud Text-to-Speech' API
- GSODR: Global Surface Summary of the Day ('GSOD') Weather Data Client
- hydroscoper: Interface to the Greek National Data Bank for Hydrometeorological Information
- MODIStsp: A Tool for Automating Download and Preprocessing of MODIS Land Products Data
- nasapower: NASA POWER API Client
- opencage: Interface to the OpenCage API
- osmdata: Import 'OpenStreetMap' Data as Simple Features or Spatial Objects
- weathercan: Download Weather Data from the Environment and Climate Change Canada Website
- wateRinfo: Download Time Series Data from Waterinfo.be
- USAboundariesData: Datasets for the 'USAboundaries' package
- USAboundaries: Historical and Contemporary Boundaries of the United States of America
- tidyhydat: Extract and Tidy Canadian 'Hydrometric' Data
- stats19: Work with Open Road Traffic Casualty Data from Great Britain
- smapr: Acquisition and Processing of NASA Soil Moisture Active-Passive (SMAP) Data
- rWBclimate: A package for accessing World Bank climate data
- rusda: Interface to USDA Databases
- rsnps: Get 'SNP' ('Single-Nucleotide' 'Polymorphism') Data on the Web
- rrricanesdata: Data for Atlantic and east Pacific tropical cyclones since 1998
- rrricanes: Web scraper for Atlantic and east Pacific hurricanes and tropical storms
- ropenaq: Accesses Air Quality Data from the Open Data Platform OpenAQ
- rnoaa: 'NOAA' Weather Data from R
- rnaturalearth: World Map Data from Natural Earth
- riem: Accesses Weather Data from the Iowa Environment Mesonet
- rgpdd: R Interface to the Global Population Dynamics Database
- rdhs: API Client and Dataset Management for the Demographic and Health Survey (DHS) Data
- rdefra: Interact with the UK AIR Pollution Database from DEFRA
- prism: Access Data from the Oregon State Prism Climate Project

Cleaning / exploring data: 

- cleanEHR: The Critical Care Clinical Data Processing Tools
- colocr: Conduct Co-localization Analysis of Fluorescence Microscopy Images
- cRegulome: Obtain and Visualize Regulome-Gene Expression Correlations in Cancer
- EndoMineR: Functions to mine endoscopic and associated pathology datasets
- geoaxe: Split 'Geospatial' Objects into Pieces
- hddtools: Hydrological Data Discovery Tools
- isdparser: Parse 'NOAA' Integrated Surface Data Files
- visdat: Preliminary Visualisation of Data
- skimr: A frictionless, pipeable approach to dealing with summary statistics


## Learn more

- ROpenSci
- The R Journal
- CRAN task views?
- ROpenSci articles?
- JOSS?